language: python
python:
  - 'nightly'
  - '3.7'
  - '3.6'

matrix:
  include:
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install: true
script:
  - python tests.py

after_success:
  - coveralls